# Generated by Django 4.2.2 on 2023-07-20 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MumChaApp', '0002_rename_posting_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
