# Generated by Django 4.2.2 on 2023-07-30 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MumChaApp', '0003_post_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birth',
        ),
        migrations.RemoveField(
            model_name='user',
            name='img',
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
