# Generated by Django 4.2.3 on 2023-07-31 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MumChaApp', '0005_alter_post_img_alter_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
