# Generated by Django 4.2.3 on 2023-07-31 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MumChaApp', '0006_remove_post_owner_delete_favorite_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=200, null=True)),
                ('post_date', models.DateTimeField()),
                ('img', models.ImageField(null=True, upload_to='images/post/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MumChaApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('fav_id', models.IntegerField(primary_key=True, serialize=False)),
                ('contents', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MumChaApp.post')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MumChaApp.user')),
            ],
        ),
    ]
