# Generated by Django 4.2.2 on 2023-07-31 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MumChaApp', '0009_rename_img_post_image_alter_post_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth',
            field=models.DateField(null=True),
        ),
    ]
