# Generated by Django 4.2.2 on 2023-07-31 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MumChaApp', '0010_user_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birth',
        ),
    ]
